// Generated by prepare-github-folder.cjs — edit reading-tracker-suite/shared/drive-api-config.cjs
window.DRIVE_PILOT_CONFIG = {
  "fileId": "",
  "apiKey": "AIzaSyDVmKapHCxPx3PRrkFZz7wlUvJm1WfVpMA",
  "tenantsJsonUrl": "tenants.json"
};
